<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<PackageId>ComparableLibrary</PackageId>
	<Version>2.0.1</Version>
	<Description>Nuget package give an opportunity for comparing objects by their values.</Description>
	<Authors>tereschvlad</Authors>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageProjectUrl>https://github.com/tereschvlad/ComparableSolution</PackageProjectUrl>
	<RepositoryUrl>https://github.com/tereschvlad/ComparableSolution</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageReadmeFile>README_NUGET.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README_NUGET.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	<None Include="..\LICENSE">
	  <Pack>True</Pack>
	  <PackagePath>\</PackagePath>
	</None>
	<None Include="..\NOTICE">
	  <Pack>True</Pack>
	  <PackagePath>\</PackagePath>
	</None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.11" />
  </ItemGroup>

</Project>
